# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'farmassist.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import sqlite3
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        # MainWindow.resize(1125, 708)
        MainWindow.resize(1125, 820)
        MainWindow.setAcceptDrops(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(70, 70, 961, 91))
        self.frame.setStyleSheet("background-color: rgb(57, 87, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(300, 30, 381, 31))
        font = QtGui.QFont()
        font.setFamily("Algerian")
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        

        # State
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(210, 190, 141, 22))
        self.comboBox.setObjectName("comboBox")
        self.label_State = QtWidgets.QLabel(self.centralwidget)
        self.label_State.setGeometry(QtCore.QRect(110, 190, 55, 16))
        self.label_State.setObjectName("label_State")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        
        
        

        # Season
        self.comboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_2.setGeometry(QtCore.QRect(210, 230, 141, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.label_Season = QtWidgets.QLabel(self.centralwidget)
        self.label_Season.setGeometry(QtCore.QRect(110, 230, 55, 16))
        self.label_Season.setObjectName("label_Season")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        
        # Budget
        self.label_Budget = QtWidgets.QLabel(self.centralwidget)
        self.label_Budget.setGeometry(QtCore.QRect(110, 280, 55, 16))
        self.label_Budget.setObjectName("label_Budget")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(210, 280, 141, 22))
        self.lineEdit.setObjectName("lineEdit")

        # Land
        self.label_Land = QtWidgets.QLabel(self.centralwidget)
        self.label_Land.setGeometry(QtCore.QRect(110, 320, 91, 16))
        self.label_Land.setObjectName("label_Land")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(210, 320, 141, 22))
        self.lineEdit_2.setObjectName("lineEdit_2")

        # Submit Button
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(210, 370, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.submit)

        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(420, 170, 20, 251))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")

        self.label_text = QtWidgets.QLabel(self.centralwidget)
        self.label_text.setGeometry(QtCore.QRect(450, 170, 571, 271))
        self.label_text.setObjectName("label_text")

        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(80, 460, 931, 87))
        self.textEdit.setObjectName("")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)

        self.menubar.setGeometry(QtCore.QRect(0, 0, 1125, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    
    def submit(self):
        print("clicked")
        # Connect With The  Database
        conn = sqlite3.connect('farmassist_guide.sqlite')
        cur = conn.cursor()
        ans=cur.execute("SELECT * FROM crop WHERE northern IS NOT NULL")    #get all the values in the column in the database
        ans=cur.fetchall()                                                  #fetch the output
        ans=list(ans[0][5:-1])                                              #remove null values by converting into a list and using slice operator

        sta = self.comboBox.currentText()
        se = self.comboBox_2.currentText()
        money = int(self.lineEdit.text())
        acers = int(self.lineEdit_2.text())

        ns = sta in ans[0]                                                  #in operator return bool values
    
        if ns:
            print("north")
            if money >= 50000 and acers >= 10:
                print("North High")
                cur.execute("SELECT nh FROM crop WHERE season=?",[se])
                dd = cur.fetchall()
                dd = str(dd[0])[2:-3]

                self.label_text.setPixmap(QtGui.QPixmap("D:\Projects\Python\FarmerAssist\img\\"+dd+".png"))
                print(dd)
            else:
                print("North Low")
                cur.execute("SELECT nl FROM crop WHERE season=?",[se])
                dd = cur.fetchall()
                dd = str(dd[0])[2:-3]
                self.label_text.setPixmap(QtGui.QPixmap("D:\Projects\Python\FarmerAssist\img\\"+dd+".png"))
                print(dd)
        else:
            print("South")
            if money >= 50000 and acers >= 10:
                print("South High")
                cur.execute("SELECT sh FROM crop WHERE season=?",[se])
                dd = cur.fetchall()
                dd = str(dd[0])[2:-3]
                self.label_text.setPixmap(QtGui.QPixmap("D:\Projects\Python\FarmerAssist\img\\"+dd+".png"))
                print(dd)
            else:
                print("South Low")
                cur.execute("SELECT sl FROM crop WHERE season=?",[se])
                dd = cur.fetchall()
                dd = str(dd[0])[2:-3]
                self.label_text.setPixmap(QtGui.QPixmap("D:\Projects\Python\FarmerAssist\img\\"+dd+".png"))
                print(dd)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.label_text.setPixmap(QtGui.QPixmap("D:\Projects\Python\armerAssist\img\main.png"))
        MainWindow.setWindowTitle(_translate("MainWindow", "Farmer Assistant"))
        self.label.setText(_translate("MainWindow", "Farmer Assistant"))
        
        #Labeling States in Combobox
        self.label_State.setText(_translate("MainWindow", "State"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Select State"))
        # self.comboBox.setItemText(0, _translate("MainWindow", "Chandigarh"))                   
        self.comboBox.setItemText(1, _translate("MainWindow", "Delhi"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Haryana"))
        self.comboBox.setItemText(3, _translate("MainWindow", "Himachal Pradesh"))
        self.comboBox.setItemText(4, _translate("MainWindow", "Jammu  Kashmir"))
        self.comboBox.setItemText(5, _translate("MainWindow", "Ladakh"))
        self.comboBox.setItemText(6, _translate("MainWindow", "Punjab"))
        self.comboBox.setItemText(7, _translate("MainWindow", "Rajasthan"))
        self.comboBox.setItemText(8, _translate("MainWindow", "Uttarakhand"))
        self.comboBox.setItemText(9, _translate("MainWindow", "Uttar Pradesh"))
        self.comboBox.setItemText(10, _translate("MainWindow", "Madhya Pradesh"))
        self.comboBox.setItemText(11, _translate("MainWindow", "West Bengal"))
        self.comboBox.setItemText(12, _translate("MainWindow", "Bihar"))
        self.comboBox.setItemText(13, _translate("MainWindow", "Gujarat"))
        self.comboBox.setItemText(14, _translate("MainWindow", "Andhra Pradesh"))
        self.comboBox.setItemText(15, _translate("MainWindow", "Karnataka"))
        self.comboBox.setItemText(16, _translate("MainWindow", "Kerala"))
        self.comboBox.setItemText(17, _translate("MainWindow", "Lakshadweep"))
        self.comboBox.setItemText(18, _translate("MainWindow", "Puducherry"))
        self.comboBox.setItemText(19, _translate("MainWindow", "Tamil Nadu"))
        self.comboBox.setItemText(20, _translate("MainWindow", "Telangana"))
        self.comboBox.setItemText(21, _translate("MainWindow", "Chennai"))
        self.comboBox.setItemText(22, _translate("MainWindow", "Bengaluru"))
        self.comboBox.setItemText(23, _translate("MainWindow", "Hyderabad"))
        self.comboBox.setItemText(24, _translate("MainWindow", "Kochi"))
        self.comboBox.setItemText(25, _translate("MainWindow", "Warangal"))
        self.comboBox.setItemText(26, _translate("MainWindow", "Thiruvananthapuram"))
        self.comboBox.setItemText(27, _translate("MainWindow", "Coimbatore"))
        self.comboBox.setItemText(28, _translate("MainWindow", "Visakhapatanam"))
        self.comboBox.setItemText(29, _translate("MainWindow", "Mysuru"))
        self.comboBox.setItemText(30, _translate("MainWindow", "Madurai"))
        self.comboBox.setItemText(31, _translate("MainWindow", "Vijayawada"))
        self.comboBox.setItemText(32, _translate("MainWindow", "Kozhikode"))
        
        
        self.label_Season.setText(_translate("MainWindow", "Season"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "Select Season"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "Kharif"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "Rabi"))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "Zaid"))


        self.label_Budget.setText(_translate("MainWindow", "Budget"))
        self.label_Land.setText(_translate("MainWindow", "Land (in Acers)"))
        self.pushButton.setText(_translate("MainWindow", "Submiit"))
        self.label_text.setText(_translate("MainWindow", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
 